### ISSUE TITLE
Running build.sh again after error doesn't work

### ISSUE THREAD

**Issue by mehlon** [Obscurix/Obscurix#1]
After getting an error with `./build.sh -v` I tried to fix it, but then running `build.sh` again gave me:
`mount: /Obscurix/work/x86_64/airootfs/proc: proc already mounted or mount point busy.`
I'm not sure how to fix this without rebooting. It would be nice if the script could clean up all the mounts  upon encountering an error.

**Comment by mehlon** [comment]
I managed to manually fix it by unmounting these first:
```
/dev/pts
/dev/shm
/sys/firmware/efi/efivars
```
And then everything else with a wildcard `*`.

**Comment by Obscurix** [comment]
The script exits immediately on errors due to `set -e`. There's no way to clean up the mounts before exiting.

You need to unmount all directories in `work/`. You don't need to unmount `/dev/pts`, `/dev/shm` or `/sys/firmware/efi/efivars`.
